name: Publish Docker File
on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with: 
          images: ramosh99/doodle_app

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with: 
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
